name: event
on: 
  push: 
    branches: 
    - main
  pull_request: 
   types: opened
   branches:
     - feature        
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: onestep
        run: echo " Event Triggered from ${{github.ref_name}} "
  feature:
    runs-on: ubuntu-latest
    steps:
      - name: testfeature branch on pullrequest
        run: echo "executing"
