name: event
on: 
  pull_request: 
    branches: 
    - feature
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: onestep
        run: echo " Event Triggered from ${{github.ref_name}} "
