name: event

on:
  pull_request:
    branches:
      - main

    types:
      - reopened
      - synchronize
      - closed

jobs:
  test:
    runs-on: ubuntu-latest.

    steps:
      - name: pull-request-closed
        if: github.event.pull_request.commits == true
        run: echo "This workflow is triggered because a pull request was closed and merged"
