name: Steps Context Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:

      - name: Generate Version
        id: Info

        run: |
          echo "context=I'm learning steps context" >> $GITHUB_OUTPUT

      - name: Print Version

        run: |
          echo "Info = ${{ steps.Info.outputs.context }}"

      - name: status
        run: | 
          echo "job status: ${{steps.Info.outcome}}"
      
