name: test
on: workflow_dispatch
jobs:
  test:
    env:
      NAME: "Sony"
    runs-on: ubuntu-latest
    steps:
     - name: test-step
       run: echo "test me"
     - name: shell-script
       run: |
        ls
        echo "I'm ${{env.NAME}}"
  
